/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblio;

import javax.swing.JFrame;
import vista.Cliente.ClienteAgregar;
import vista.Compra.LibroComprar;
import vista.Libro.LibroAgregar;
import vista.Compra.LibrosComprados;
import vista.Libro.LibroInventario;
import vista.Trabajador.TrabajadorAgregar;
import vista.Venta.LibroVenta;
import vista.Venta.LibrosVendidos;
import vistaArriendo.LibroArriendo;
import vistaArriendo.LibrosArrendados;
import vistas.Distribuidor.DistribuidorAgregar;

/**
 *
 * @author daniela
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCompra = new javax.swing.JMenu();
        itemLibrosComprados = new javax.swing.JMenuItem();
        itemCompraLibro = new javax.swing.JMenuItem();
        menuVenta = new javax.swing.JMenu();
        itemLibrosVendidos = new javax.swing.JMenuItem();
        itemLibroVenta = new javax.swing.JMenuItem();
        menuArriendo = new javax.swing.JMenu();
        itemLibrosArrendados = new javax.swing.JMenuItem();
        itemArrendarLibro = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemInventarioLibro = new javax.swing.JMenuItem();
        itemAgregarLibro = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        itemAgregarTrabajador = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        itemAgreCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        Agregar = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Biblioteca especializada FastDevelopment");

        menuCompra.setText("Compra");

        itemLibrosComprados.setText("Libros Comprados");
        itemLibrosComprados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLibrosCompradosActionPerformed(evt);
            }
        });
        menuCompra.add(itemLibrosComprados);

        itemCompraLibro.setText("Comprar Libro");
        itemCompraLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCompraLibroActionPerformed(evt);
            }
        });
        menuCompra.add(itemCompraLibro);

        jMenuBar1.add(menuCompra);

        menuVenta.setText("Venta");

        itemLibrosVendidos.setText("Libros Vendidos");
        itemLibrosVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLibrosVendidosActionPerformed(evt);
            }
        });
        menuVenta.add(itemLibrosVendidos);

        itemLibroVenta.setText("Vender Libros");
        itemLibroVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLibroVentaActionPerformed(evt);
            }
        });
        menuVenta.add(itemLibroVenta);

        jMenuBar1.add(menuVenta);

        menuArriendo.setText("Arriendo");

        itemLibrosArrendados.setText("Libros Arrendados");
        itemLibrosArrendados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLibrosArrendadosActionPerformed(evt);
            }
        });
        menuArriendo.add(itemLibrosArrendados);

        itemArrendarLibro.setText("Arrendar Libros");
        itemArrendarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemArrendarLibroActionPerformed(evt);
            }
        });
        menuArriendo.add(itemArrendarLibro);

        jMenuBar1.add(menuArriendo);

        jMenu3.setText("Libros");

        itemInventarioLibro.setText("Inventario");
        itemInventarioLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInventarioLibroActionPerformed(evt);
            }
        });
        jMenu3.add(itemInventarioLibro);

        itemAgregarLibro.setText("Agregar Libro");
        itemAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarLibroActionPerformed(evt);
            }
        });
        jMenu3.add(itemAgregarLibro);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Trabajadores");

        jMenuItem9.setText("Ver Trabajador");
        jMenu4.add(jMenuItem9);

        itemAgregarTrabajador.setText("Agregar Trabajador");
        itemAgregarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarTrabajadorActionPerformed(evt);
            }
        });
        jMenu4.add(itemAgregarTrabajador);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Clientes");

        jMenuItem11.setText("Ver Cliente");
        jMenu5.add(jMenuItem11);

        itemAgreCliente.setText("Agregar Cliente");
        itemAgreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgreClienteActionPerformed(evt);
            }
        });
        jMenu5.add(itemAgreCliente);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Proveedor");

        jMenuItem2.setText("Ver Proveedor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        Agregar.setText("Agregar Proveedor");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jMenu2.add(Agregar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void itemInventarioLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInventarioLibroActionPerformed
        LibroInventario inventarioLib = new LibroInventario();
        inventarioLib.setVisible(true);
    }//GEN-LAST:event_itemInventarioLibroActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
       DistribuidorAgregar agregarDis = new DistribuidorAgregar();
               
       agregarDis.setVisible(true);
      
    }//GEN-LAST:event_AgregarActionPerformed

    private void itemAgreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgreClienteActionPerformed
        ClienteAgregar agregarCli =  new ClienteAgregar();
        agregarCli.setVisible(true);
        
    }//GEN-LAST:event_itemAgreClienteActionPerformed

    private void itemAgregarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarTrabajadorActionPerformed
        TrabajadorAgregar agregarTra = new TrabajadorAgregar();
        agregarTra.setVisible(true);
    }//GEN-LAST:event_itemAgregarTrabajadorActionPerformed

    private void itemAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarLibroActionPerformed
        LibroAgregar agregarLib = new LibroAgregar();
        agregarLib.setVisible(true);
    }//GEN-LAST:event_itemAgregarLibroActionPerformed

    private void itemLibrosCompradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLibrosCompradosActionPerformed
        LibrosComprados compradosLib = new LibrosComprados();
        compradosLib.setVisible(true);
    }//GEN-LAST:event_itemLibrosCompradosActionPerformed

    private void itemCompraLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCompraLibroActionPerformed
        LibroComprar compraLib = new LibroComprar();
        compraLib.setVisible(true);
        
    }//GEN-LAST:event_itemCompraLibroActionPerformed

    private void itemLibrosVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLibrosVendidosActionPerformed
        LibrosVendidos vendidosLib = new LibrosVendidos();
        vendidosLib.setVisible(true);
    }//GEN-LAST:event_itemLibrosVendidosActionPerformed

    private void itemLibroVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLibroVentaActionPerformed
        LibroVenta ventaLib = new LibroVenta();
        ventaLib.setVisible(true);
        
    }//GEN-LAST:event_itemLibroVentaActionPerformed

    private void itemLibrosArrendadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLibrosArrendadosActionPerformed
        LibrosArrendados arrendadosLib = new LibrosArrendados();
        arrendadosLib.setVisible(true);
        
    }//GEN-LAST:event_itemLibrosArrendadosActionPerformed

    private void itemArrendarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemArrendarLibroActionPerformed
        LibroArriendo arriendoLib = new LibroArriendo();
        arriendoLib.setVisible(true);
    }//GEN-LAST:event_itemArrendarLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Agregar;
    private javax.swing.JMenuItem itemAgreCliente;
    private javax.swing.JMenuItem itemAgregarLibro;
    private javax.swing.JMenuItem itemAgregarTrabajador;
    private javax.swing.JMenuItem itemArrendarLibro;
    private javax.swing.JMenuItem itemCompraLibro;
    private javax.swing.JMenuItem itemInventarioLibro;
    private javax.swing.JMenuItem itemLibroVenta;
    private javax.swing.JMenuItem itemLibrosArrendados;
    private javax.swing.JMenuItem itemLibrosComprados;
    private javax.swing.JMenuItem itemLibrosVendidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuArriendo;
    private javax.swing.JMenu menuCompra;
    private javax.swing.JMenu menuVenta;
    // End of variables declaration//GEN-END:variables
}
